import React from "react";

const Policy: React.FC = () => {
    return (
        <section id="policy-details" className="container mx-auto px-4 py-12 text-gray-200">
            <h1 className="text-6xl font-bold mb-6">Datenschutzerklärung</h1>

            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Verantwortliche Stelle und Kontakt</h2>
            <p className="mb-4">
                Verantwortlicher im Sinne des Art. 4 Nr. 7 DSGVO (Datenschutz-Grundverordnung) für die Datenverarbeitungen auf der Second-Level-Domain zacklack.de einschließlich aller zugehörigen Subdomains ist:                
                <br /><br />
                <em>Name:</em> Cédric
                <br />
                <em>Anschrift:</em> Auf Anfrage, kontaktieren sie uns unter unserer E-Mail Adresse.
                <br />
                <em>Telefon:</em> Auf Anfrage, kontaktieren sie uns unter unserer E-Mail Adresse.
                <br />
                E-Mail:{" "}
                <a href="mailto:webmaster@zacklack.de" className="text-blue-400 underline">
                    webmaster@zacklack.de
                </a>
                <br /><br />
                Es ist kein Datenschutzbeauftragter bestellt, da die gesetzlichen Voraussetzungen einer Bestellpflicht nicht vorliegen (Art. 37 DSGVO). Bei Fragen zum Datenschutz können Sie sich daher direkt an den Verantwortlichen wenden.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">2. Begriffsbestimmungen</h2>
            <p className="mb-4">
                Diese Datenschutzerklärung verwendet Begriffe im Sinne der DSGVO. Zur besseren Verständlichkeit werden wichtige datenschutzrechtliche Begriffe vorab erläutert (vgl. Art. 4 DSGVO):
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>Personenbezogene Daten:</strong> Alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen. Eine Person gilt als identifizierbar, wenn sie direkt oder indirekt, insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, einer Kennnummer, Standortdaten, einer Online-Kennung oder besonderen Merkmalen identifiziert werden kann. Dazu gehören z.B. Name, Anschrift, E-Mail-Adresse, aber auch IP-Adressen oder Gerätekennungen.</li>
                    <li><strong>Betroffene Person:</strong> Jede identifizierte oder identifizierbare natürliche Person, deren personenbezogene Daten verarbeitet werden (also z.B. Sie als Besucher*in dieser Website).</li>
                    <li><strong>Verarbeitung:</strong> Jeder Vorgang im Zusammenhang mit personenbezogenen Daten, egal ob automatisiert oder manuell, wie etwa das Erheben, das Erfassen, die Organisation, das Speichern, das Anpassen oder Verändern, das Auslesen, Abfragen, Verwenden, Offenlegen durch Übermittlung, Verbreiten oder eine andere Form der Bereitstellung, der Abgleich, die Verknüpfung, Einschränkung, das Löschen oder die Vernichtung von Daten.</li>
                    <li><strong>Verantwortlicher:</strong> Die Person oder Stelle, die allein oder gemeinsam über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet – hier also der oben genannte Webseitenbetreiber.</li>
                    <li><strong>Auftragsverarbeiter:</strong> Eine Person oder Stelle, die personenbezogene Daten im Auftrag des Verantwortlichen verarbeitet (Art. 4 Nr. 8 DSGVO). Beispiel: Ein externer Dienstleister, der in unserem Auftrag Daten hostet.</li>
                    <li><strong>Empfänger:</strong> Eine Person oder Stelle, der personenbezogene Daten offengelegt werden – unabhängig davon, ob es sich um einen Dritten im datenschutzrechtlichen Sinne handelt oder nicht (Art. 4 Nr. 9 DSGVO). Behörden, die im Rahmen eines gesetzlichen Auftrags Daten erhalten, gelten jedoch nicht als Empfänger.</li>
                    <li><strong>Dritter:</strong> Jede Person oder Stelle außerhalb der betroffenen Person, des Verantwortlichen, des Auftragsverarbeiters und der Personen, die unter der unmittelbaren Verantwortung des Verantwortlichen oder des Auftragsverarbeiters befugt sind, Daten zu verarbeiten.</li>
                    <li><strong>Einwilligung:</strong> Jede freiwillig und in informierter Weise durch eine eindeutige bestätigende Handlung abgegebene Willensbekundung, mit der die betroffene Person zu verstehen gibt, dass sie mit der Verarbeitung der sie betreffenden personenbezogenen Daten einverstanden ist (Art. 4 Nr. 11 DSGVO). Eine Einwilligung kann gemäß Art. 7 DSGVO jederzeit für die Zukunft widerrufen werden.</li>
                </ul>
                <br />
                <em>Hinweis: Weitere Begriffsbestimmungen können Art. 4 DSGVO entnommen werden. Wir verwenden die obigen Definitionen in dieser Datenschutzerklärung, um möglichst präzise auszudrücken, welche Daten wir wie verarbeiten.</em>
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">3. Gegenstand und Geltungsbereich dieser Datenschutzerklärung</h2>
            <p className="mb-4">
                Diese Datenschutzerklärung informiert Sie darüber, welche personenbezogenen Daten auf der Domain zacklack.de und allen zugehörigen Subdomains erhoben werden, zu welchen Zwecken wir diese Daten verwenden und wie wir sie verarbeiten. Sie gilt für alle Webseiten-Inhalte unter zacklack.de einschließlich Unterseiten und Subdomains (insbesondere legal.zacklack.de für rechtliche Hinweise, quiz.zacklack.de für interaktive Quiz-Angebote, cedric.zacklack.de als persönliche Portfolio-Seite des Betreibers, sowie weitere Dienste wie privat.zacklack.de, wakapi.zacklack.de etc.).
                <br /><br />
                Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften – insbesondere der DSGVO, dem Bundesdatenschutzgesetz (BDSG), dem Telekommunikation-Telemedien-Datenschutz-Gesetz (TTDSG) sowie der ePrivacy-Richtlinie 2002/58/EG – und dieser Datenschutzerklärung.
                <br /><br />
                Bitte beachten Sie, dass wir uns vorbehalten, diese Datenschutzerklärung bei Bedarf anzupassen, etwa bei Einführung neuer Dienste oder Änderungen der Rechtslage. Die jeweils aktuelle Fassung wird an dieser Stelle veröffentlicht.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">4. Allgemeine Hinweise zur Datenverarbeitung auf unserer Website</h2>
            <p className="mb-4">
                <strong>Umfang der Verarbeitung:</strong> Wir verarbeiten personenbezogene Daten unserer Nutzer nur, soweit dies zur Bereitstellung eines funktionsfähigen Webangebots sowie unserer Inhalte und Leistungen erforderlich ist. Grundsätzlich erfolgt die Nutzung unserer Website ohne aktive Angabe personenbezogener Daten durch Sie (es existieren keine klassischen Benutzerkonten oder Formulareingaben für öffentliche Nutzer). Dennoch werden bei der Nutzung – vor allem technisch bedingt – einige Daten automatisch verarbeitet (siehe unten). Sofern Sie bestimmte geschützte Bereiche nutzen (Login-Bereich) oder unsere interaktiven Dienste aufrufen, kann es zur Verarbeitung weiterer Daten (z.B. Ihrer E-Mail-Adresse zur Verifikation) kommen. In keinem Fall erfolgt eine Verarbeitung Ihrer Daten zu Werbezwecken oder Profilbildung ohne Ihre ausdrückliche Einwilligung.
                <br /><br />
                <strong>Rechtsgrundlagen:</strong> Soweit wir für Verarbeitungsvorgänge eine Einwilligung von Ihnen einholen, dient Art. 6 Abs. 1 lit. a DSGVO als Rechtsgrundlage. Ist die Verarbeitung zur Erfüllung eines Vertrags oder vorvertraglicher Maßnahmen erforderlich (z.B. Nutzung eines von uns angebotenen Dienstes, für den Sie sich registriert haben), erfolgt sie auf Basis von Art. 6 Abs. 1 lit. b DSGVO. In den meisten Fällen stützen wir die Datenverarbeitung auf berechtigte Interessen nach Art. 6 Abs. 1 lit. f DSGVO – etwa unser Interesse an der technisch fehlerfreien Bereitstellung und Sicherheit der Website, an der Verbesserung unseres Angebots oder der Beantwortung von Anfragen. In solchen Fällen prüfen wir stets, dass keine überwiegenden Interessen oder Grundrechte Ihrerseits entgegenstehen. Zudem werden im erforderlichen Umfang die spezialgesetzlichen Regelungen des TTDSG berücksichtigt (siehe insbesondere § 25 TTDSG für den Einsatz von Cookies und ähnlichen Technologien). Technisch notwendige Cookies oder Zugriffe, die ausschließlich der Übertragung einer Nachricht oder der Bereitstellung eines von Ihnen gewünschten Dienstes dienen, erfolgen auf Grundlage von § 25 Abs. 2 Nr. 2 TTDSG (keine Einwilligung erforderlich). Für alle anderen Fälle holen wir eine Einwilligung nach § 25 Abs. 1 TTDSG ein (etwa über eine Cookie-Einwilligung, sofern nicht bereits durch die Konfiguration des Browsers erteilt).
                <br /><br />
                <strong>Sicherheitsmaßnahmen:</strong> Wir haben umfangreiche technische und organisatorische Maßnahmen getroffen, um Ihre Daten nach dem Stand der Technik zu schützen. Dennoch weisen wir darauf hin, dass die Datenübertragung im Internet stets Sicherheitslücken aufweisen kann (vgl. Erwägungsgrund 49 DSGVO) – ein absoluter Schutz ist nicht garantiert. Insbesondere bei der Übertragung von Daten via Internet (z.B. Kommunikation per E-Mail) kann kein lückenloser Schutz vor dem Zugriff Dritter gewährleistet werden. Wir bitten Sie, dies bei der Nutzung unseres Webangebots zu berücksichtigen.
                <br /><br />
                <strong>Weitergabe in Drittländer:</strong> Wo wir Dienste von Anbietern außerhalb der EU/EWR einsetzen (insbesondere in den USA), stellen wir sicher, dass ein angemessenes Datenschutzniveau gewährleistet ist. Für bestimmte US-Dienstleister besteht ein Angemessenheitsbeschluss gemäß Art. 45 DSGVO – diese sind unter dem EU–US Data Privacy Framework zertifiziert, wodurch die Europäische Kommission ein angemessenes Schutzniveau in den USA anerkennt. Wo wir auf nicht zertifizierte Anbieter zurückgreifen, erfolgen Übermittlungen auf Grundlage von Standarddatenschutzklauseln nach Art. 46 Abs. 2 lit. c DSGVO und ggf. zusätzlichen Maßnahmen. Wir weisen jedoch darauf hin, dass in solchen Fällen ein gewisses Restrisiko bestehen kann, da US-Behörden unter Umständen Zugriff auf personenbezogene Daten nehmen können (Stichwort CLOUD Act); dies wurde auch durch das Schrems II-Urteil des EuGH hervorgehoben. Sollte keine der genannten Garantien greifen, holen wir Ihre ausdrückliche Einwilligung nach Art. 49 Abs. 1 lit. a DSGVO ein, bevor wir Daten in ein unsicheres Drittland übermitteln.
                <br /><br />
                Im Folgenden erläutern wir im Detail, welche Datenverarbeitungsvorgänge stattfinden, wenn Sie unser Webangebot nutzen, und nennen die jeweiligen Zwecke, Rechtsgrundlagen, Empfänger und Schutzmaßnahmen.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">5. Bereitstellung der Website und Server-Logfiles</h2>
            <p className="mb-4">
                <strong>Beschreibung der Verarbeitung:</strong> Bei jedem Aufruf unserer Website zacklack.de (inklusive ihrer Subdomains) verarbeitet unser System automatisiert folgende Informationen von Ihrem Endgerät:
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>Log-Daten:</strong> Dazu zählen die IP-Adresse Ihres Geräts, Datum und Uhrzeit des Zugriffs, die aufgerufene Seite/Datei und URL (Request), der HTTP-Statuscode, die übertragene Datenmenge, Browsertyp und Version, das verwendete Betriebssystem, die zuvor besuchte Seite (Referrer-URL, falls übermittelt) sowie ggf. weitere technische Informationen (wie z.B. Spracheinstellung des Browsers). Diese Daten fallen automatisch an, wenn Ihr Browser eine Webseite anfragt.</li>
                    <li><strong>Hosting und Infrastruktur:</strong> Unsere Website wird über folgende Infrastrukturen bereitgestellt: Cloudflare Pages (ein Hosting-Dienst der Cloudflare, Inc., USA), ein selbst verwalteter Server mit Coolify (Open-Source-Hosting-Software) sowie ein cloudbasiertes Backend auf Railway (Railway, Inc., USA). Die anfallenden Log-Daten können daher von diesen Infrastruktur-Anbietern verarbeitet werden, die in unserem Auftrag handeln (als Auftragsverarbeiter). Cloudflare fungiert zusätzlich als Content Delivery Network (CDN) und Web Application Firewall (WAF) vor unserem Angebot – d.h. Ihre Webanfragen laufen zunächst durch das globale Cloudflare-Netzwerk, welches schädliche Anfragen filtert und Inhalte zwischenspeichert. Dabei werden Protokolldaten über Ereignisse in deren Netzwerk aufgezeichnet. Cloudflare verarbeitet diese Informationen in ihren Haupt-Rechenzentren in den USA und Europa für einen begrenzten Zeitraum. Insbesondere speichert Cloudflare im Rahmen eines Bot-Managements die IP-Adressen der auf unsere Seiten zugreifenden Endgeräte, um zwischen menschlichen Zugriffen und automatisierten Bots zu unterscheiden und missbräuchliche Anfragen (z.B. DDoS-Angriffe oder Scraping) abzuwehren. Hierzu setzt Cloudflare auch ein Cookie "__cf_bm" (bot management) mit kurzer Lebensdauer (i.d.R. 30 Minuten) auf Ihrem Gerät, das technisch notwendig ist, um Ihren Request im Cloudflare-Netz zu identifizieren (dies dient ausschließlich der Funktionssicherheit und nicht dem Tracking; vgl. § 25 Abs. 2 Nr. 2 TTDSG).</li>
                </ul>
                <br />
                <strong>Zwecke:</strong> Die Verarbeitung dieser Log- und Verbindungsdaten erfolgt, um den Verbindungsaufbau und die Auslieferung der Website an Ihr Gerät zu ermöglichen, die Sicherheit und Stabilität des Betriebs zu gewährleisten sowie ggf. Fehler zu analysieren und Angriffsversuche abzuwehren. Hierin liegt zugleich unser berechtigtes Interesse an der Datenverarbeitung. Eine Zusammenführung dieser Daten mit anderen Datenquellen erfolgt nicht, wir verwenden die Logfiles insbesondere nicht zu Marketing- oder Profilbildungszwecken.
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Bereitstellung einer funktionsfähigen und sicheren Website). Die Gewährleistung von Netz- und Informationssicherheit ist als berechtigtes Interesse im Sinne der DSGVO anerkannt. Soweit die Speicherung von Informationen in Ihrem Endgerät erfolgt (z.B. Setzen des Cloudflare-Cookies), beruht dies auf § 25 Abs. 2 TTDSG (technisch zwingend notwendig für die Bereitstellung des Dienstes, daher einwilligungsfrei).
                <br /><br />
                <strong>Empfänger und Weitergabe:</strong> Empfänger der vorstehenden Daten sind zunächst wir als Betreiber, d.h. die Daten werden auf unseren Server-Protokollen erfasst. Darüber hinaus erhalten unsere Hosting-Dienstleister Zugriff auf die Daten als Auftragsverarbeiter:
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>Cloudflare, Inc.</strong>, 101 Townsend St., San Francisco, CA 94107, USA (Cloudflare Germany GmbH, Rosental 7, c/o Mindspace, 80331 München als EU-Vertreter) – für CDN, DNS und Sicherheitsdienste. Cloudflare empfängt Ihre IP-Adresse und die oben genannten Verbindungsdaten, um die Anfrage zu verarbeiten. Diese Daten können in Cloudflare-Rechenzentren außerhalb Deutschlands (u.a. USA) zwischengespeichert werden; Cloudflare ist jedoch nach dem EU–US Data Privacy Framework zertifiziert und garantiert damit ein angemessenes Datenschutzniveau. Weitere Informationen finden Sie in der Cloudflare-Datenschutzerklärung.</li>
                    <li><strong>Railway, Inc. (USA)</strong> – Plattform zur Bereitstellung unseres Backend-Servers. Ihre Anfrage (inkl. IP, angefragter URL etc.) wird an unsere Anwendung weitergeleitet, die auf Railway gehostet ist. Railway verarbeitet diese Daten technisch als Host unseres Servers. Wir haben mit Railway einen Vertrag zur Auftragsverarbeitung (Data Processing Agreement) abgeschlossen. (Hinweis: Railway ist ein US-Dienst; bei Datenübertragung in die USA stützen wir uns auf Standardvertragsklauseln, da uns keine DPF-Zertifizierung bekannt ist – siehe Abschnitt zu Drittländern oben.)</li>
                    <li><strong>Eigenes Serverhosting (Coolify):</strong> Teile unseres Angebots werden auf einer selbst gehosteten Infrastruktur betrieben, die wir mit der Open-Source-Software Coolify verwalten. Dieses System läuft auf mehreren Server, darunter ein Server mit einem i7-12650H, sowie diversen älteren Servern um Redundanz zu gewährleisten, alle Server  befinden sich unter unserer Kontrolle (Standort Berlin - Deutschland - EU), so dass hier keine externen Empfänger auftreten. Die Log-Daten werden auf diesem Server gespeichert und unterliegen denselben Zwecken und Löschfristen wie insgesamt beschrieben.</li>
                </ul>
                <br />
                Eine darüberhinausgehende aktive Weitergabe der Log-Daten an Dritte erfolgt nur im Falle einer rechtlichen Verpflichtung oder zur Strafverfolgung bei Sicherheitsvorfällen. Allerdings können die oben genannten Infrastruktur-Dienstleister im Wartungs- oder Supportfall Kenntnis von Daten erlangen (im Rahmen ihres Auftragsverarbeiter-Tätigkeit, vertraglich geregelt).
                <br /><br />
                <strong>Speicherdauer:</strong> Die Server-Logfiles (inkl. IP-Adresse) werden von uns nur vorübergehend gespeichert. Eine personenbezogene Speicherung erfolgt grundsätzlich nur so lange, wie es für die genannten Zwecke erforderlich ist. Anschließend werden die IP-Adressen anonymisiert oder die Logeinträge gelöscht. Konkret werden Zugrifflogs auf unseren Webservern in der Regel nach 30 Tagen automatisiert gelöscht bzw. anonymisiert (durch Kürzung der IP-Adresse). Cloudflare selbst hält Protokolldaten ebenfalls nur für einen begrenzten Zeitraum vor (nach unseren Informationen derzeit wenige Tage, maximal bis zu 7 Tage, sofern nicht sicherheitsrelevant). Die über Cloudflare eingesetzten Sicherheits-Cookies (__cf_bm) verfallen automatisch nach ca. 30 Minuten Inaktivität.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">6. Zugriffsgeschützte Bereiche und Authentifizierung (Cloudflare Zero Trust)</h2>
            <p className="mb-4">
                <strong>Beschreibung der Verarbeitung:</strong> Einige Subdomains unseres Angebots sind nicht öffentlich zugänglich, sondern durch einen vorgeschalteten Anmeldeprozess geschützt (Cloudflare Zero Trust Access). Beispielsweise erfordert privat.zacklack.de eine Authentifizierung, um interne Inhalte anzuzeigen. Den Zugang regeln wir über Cloudflare Access, einen Dienst von Cloudflare, Inc. Dieser Dienst überprüft, ob ein Besucher sich erfolgreich als berechtigter Nutzer ausgewiesen hat. Die Authentifizierung erfolgt OIDC-basiert über ausgewählte Identitätsanbieter (OAuth-Login) oder alternativ durch E-Mail-Code-Verifizierung. Konkret bieten wir zur Anmeldung die Möglichkeit, sich mit einem bestehenden Konto bei Google oder GitHub anzumelden (OAuth 2.0 Login), oder einen Einmal-Code an eine berechtigte E-Mail-Adresse senden zu lassen (One-Time Pin per Email):
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>OAuth-Login (Google/GitHub):</strong> Wenn Sie diese Option wählen, werden Sie auf die Anmeldeseite des jeweiligen Anbieters weitergeleitet. Dort können Sie sich mit Ihren Zugangsdaten einloggen. Unser System erhält anschließend vom Anbieter eine Rückmeldung, ob die Authentifizierung erfolgreich war, sowie bestimmte Basis-Informationen aus Ihrem Profil beim Anbieter (typischerweise Ihren Namen und Ihre E-Mail-Adresse). Im Rahmen der Cloudflare Access Integration erhalten wir vor allem Ihre E-Mail-Adresse übermittelt, ggf. auch Ihren Anzeigenamen, um Sie als berechtigten Nutzer zu identifizieren. Google LLC (1600 Amphitheatre Parkway, Mountain View, CA, USA – vertreten in der EU durch Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Irland) bzw. GitHub, Inc. (88 Colin P Kelly Jr St, San Francisco, CA, USA – Tochtergesellschaft der Microsoft Corp.) erfahren dabei, dass Sie sich bei unserem Dienst anmelden möchten. Es gelten die Datenschutzbestimmungen der jeweiligen Anbieter, auf die wir im Rahmen des OAuth-Login hinweisen. Wir selbst speichern keine OAuth-Zugangsdaten; wir erhalten lediglich von Cloudflare die benötigten Informationen (E-Mail-Adresse, Authentifizierungstoken), um den Zugang zu gewähren. Cloudflare Access setzt nach erfolgreicher Anmeldung ein Sitzungs-Cookie (CF_Authorization) in Ihrem Browser, das ein JSON Web Token enthält. Dieses Cookie bestätigt gegenüber unserer Website Ihre Zugangsberechtigung und hat eine begrenzte Gültigkeitsdauer. Es handelt sich um ein technisch notwendiges Cookie, da ohne dieses der geschützte Bereich nicht zugänglich wäre (§ 25 Abs. 2 TTDSG).</li>
                    <li><strong>E-Mail-Code-Login:</strong> Alternativ können berechtigte Nutzer einen einmaligen Login-Code per E-Mail erhalten. Hierbei gibt der Nutzer auf der Cloudflare-Access-Seite seine E-Mail-Adresse ein. Ist die Adresse in unserer Zugangsberechtigten-Liste (Access Policy) hinterlegt, sendet Cloudflare im Auftrag ein E-Mail mit einem Bestätigungscode an diese Adresse. (Cloudflare nutzt hierfür einen eigenen Mail-Server; die E-Mail-Adresse des Nutzers wird somit bei Cloudflare und dessen E-Mail-Dienstleistern verarbeitet, um den Code zuzustellen.) Der Nutzer gibt den Code auf der Website ein und erhält bei Erfolg ebenfalls das CF_Authorization-Cookie gesetzt. In diesem Prozess verarbeiten wir die eingegebene E-Mail-Adresse sowie den Zeitpunkt der Anmeldung. Die E-Mail-Adresse dient ausschließlich der Versendung des Logincodes und der Zugangskontrolle. Wir führen keine darüber hinausgehende Speicherung durch, außer in Protokollen zur Nachvollziehbarkeit von Zugriffen (siehe unten).</li>
                </ul>
                <br />
                <strong>Zwecke:</strong> Die Datenverarbeitung im Rahmen von Cloudflare Zero Trust Access erfolgt zum Zweck der Zugriffskontrolle und Berechtigungsprüfung. Sie stellt sicher, dass nur autorisierte Personen bestimmte nicht-öffentliche Bereiche unseres Webangebots einsehen oder nutzen können. Damit schützen wir vertrauliche Inhalte vor unberechtigtem Zugriff. Gleichzeitig dient die Verarbeitung der Sicherheit (Schutz vor Angriffen durch unbefugte Dritte) und der Integrität unseres Systems. Die temporäre Protokollierung der Anmeldevorgänge (welche E-Mail-Adresse wann versucht hat sich anzumelden, Erfolg/Misserfolg) erfolgt zur Nachvollziehbarkeit und ggf. Abwehr von Brute-Force-Angriffen.
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse). Unser legitimes Interesse liegt in der Zugangsbeschränkung sensibler Bereiche und der Aufrechterhaltung der Netz- und Informationssicherheit. Die Verarbeitung der Login-Daten ist dabei erforderlich und verhältnismäßig, um unbefugte Zugriffe zu verhindern, was im Einklang mit Erwägungsgrund 49 DSGVO ausdrücklich als berechtigtes Interesse anerkannt ist. Soweit im Rahmen der OAuth-Anmeldung eine Weiterleitung an Dritte (Google/GitHub) erfolgt, beruht dies auf Ihrer freiwilligen Entscheidung für diese Login-Methode; die Übermittlung Ihrer Daten an den jeweiligen Anbieter erfolgt mit Ihrer konkludenten Einwilligung (Art. 6 Abs. 1 lit. a DSGVO), indem Sie den OAuth-Login auswählen und bei dem Anbieter einloggen. Sie können jederzeit eine andere Login-Methode wählen, um diese Datenweitergabe zu vermeiden. Die Verwendung technisch notwendiger Cookies (CF_Authorization) stützen wir auf § 25 Abs. 2 Nr. 2 TTDSG.
                <br /><br />
                <strong>Empfänger:</strong> Empfänger der oben genannten Daten sind zunächst Cloudflare (als Betreiber des Zero-Trust-Dienstes) und die von Ihnen gewählten Identity-Provider (Google LLC bzw. GitHub Inc.). Cloudflare verarbeitet die Daten als Auftragsverarbeiter in unserem Auftrag, um den Anmeldedienst bereitzustellen. Google/GitHub wirken als eigenständige Verantwortliche für den Authentifizierungsvorgang – auf deren Datenverarbeitung (z.B. Ihrer bei Google gespeicherten Profildaten) haben wir keinen Einfluss; es gelten deren Datenschutzrichtlinien. Im Falle des E-Mail-Code-Logins agiert Cloudflare zugleich als technischer E-Mail-Dienst. Ihre Login-E-Mail-Adresse wird hierbei an Cloudflare und ggf. verbundene Dienstleister (E-Mail-Versand) übermittelt. Cloudflare ist, wie oben erwähnt, nach dem EU-US Datenschutzrahmen zertifiziert, sodass ein angemessenes Schutzniveau gewährleistet ist. Google ist ebenfalls entsprechend zertifiziert und den EU-Standardvertragsklauseln unterworfen, GitHub/Microsoft ebenso – somit sind Ihre Daten auch bei diesen Empfängern durch anerkannte Mechanismen geschützt. Innerhalb unseres Verantwortungsbereichs erhalten nur berechtigte Administratoren Zugriff auf die Anmeldeprotokolle, und auch dies nur zu Kontrollzwecken. Eine Nutzung der Login-Daten zu anderen Zwecken erfolgt nicht.
                <br /><br />
                <strong>Speicherdauer:</strong> Die Login-Sitzungsdaten (Cookie) werden in Ihrem Browser gespeichert, bis das Cookie abläuft (typischerweise nach einigen Stunden) oder Sie sich ausloggen bzw. das Browser-Cookie manuell löschen. Die Protokolldaten über Zugriffsversuche (E-Mail-Adresse, Zeitpunkt, Erfolg/Fehlschlag) werden von Cloudflare kurzfristig gespeichert, um sicherheitsrelevante Auswertungen zu ermöglichen. Eine konkrete Löschfrist seitens Cloudflare ist uns nicht bekannt, wir gehen aber von einer automatischen Löschung innerhalb weniger Tage bis Wochen aus, sofern kein sicherheitsrelevanter Vorfall vorliegt. Wir selbst speichern solche Anmeldedaten nicht dauerhaft außerhalb von Cloudflare. Sollten ausnahmsweise weitergehende Aufbewahrungspflichten bestehen (z.B. zur Untersuchung eines sicherheitsrelevanten Vorfalls), werden die betreffenden Daten bis zur Klärung des Vorfalls vorgehalten und anschließend gelöscht.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">7. Nutzung von Drittanbieter-Ressourcen (Scripts, Fonts und Icons)</h2>
            <p className="mb-4">
                Unser Webangebot bindet an einigen Stellen extern gehostete Ressourcen ein, um die Seiten ansprechend und funktional zu gestalten. Dabei handelt es sich insbesondere um Schriftarten und Icons. Beim Aufruf solcher Ressourcen von Drittanbietern wird – technisch bedingt – Ihre IP-Adresse an den Drittanbieter übertragen, damit dieser die Inhalte an Ihren Browser ausliefern kann. Ihre IP-Adresse ist nach herrschender Meinung als personenbezogenes Datum zu qualifizieren, da theoretisch ein Personenbezug über Ihren Internet-Provider herstellbar ist. Wir achten darauf, den Einsatz externer Ressourcen datenschutzfreundlich zu gestalten und nutzen wo möglich lokale Kopien, um unnötige Datenübermittlungen zu vermeiden. Im Einzelnen:
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>Google Fonts:</strong> Unsere Website verwendet teilweise Schriftarten von Google Fonts. Diese Schriften sind teils lokal auf unserem Webserver eingebunden, in manchen Fällen werden sie jedoch direkt vom Server des Anbieters Google nachgeladen. Anbieter ist Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Irland (Google Ireland ist verantwortlich für EU-Benutzer; der Mutterkonzern ist Google LLC, USA). Wenn Ihr Browser eine Google-Schrift von deren Server lädt, verbindet er sich zu Google und übermittelt dabei Ihre IP-Adresse und welche Seite Sie besuchen. Nach einem Urteil des LG München vom 20.01.2022 stellt eine solche Übermittlung ohne Einwilligung einen Verstoß gegen das Recht auf informationelle Selbstbestimmung dar, da die IP-Adresse personenbezogen ist und Google Fonts auch ohne direkten Abruf (durch lokalen Host) genutzt werden könnte. Wir haben daher ein berechtigtes Interesse, diese Übermittlung zu vermeiden. Soweit möglich, hosten wir Google Fonts lokal, sodass bei Aufruf unserer Seiten in der Regel keine Verbindung zu Google aufgebaut wird. Sollte in Ausnahmefällen doch eine Einbindung über Google-Server erfolgen (etwa aus technischen Gründen oder bei Nutzung bestimmter Unterseiten), erfolgt dies nur mit Ihrer vorherigen Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO i.V.m. § 25 Abs. 1 TTDSG (z.B. über unsere Cookie/Consent-Einstellungen). Ohne eine solche Einwilligung werden keine extern gehosteten Google Fonts nachgeladen. – Hinweis: Google erklärt, dass bei Nutzung von Google Fonts keine Cookies gesetzt und die übertragenen Font-Anfragen getrennt von anderen Google-Diensten ausgewertet werden. Dennoch werden Daten in die USA übertragen. Google ist unter dem Data Privacy Framework zertifiziert, wodurch ein angemessenes Niveau sichergestellt ist. Weitere Informationen finden Sie in der Datenschutzerklärung von Google (https://policies.google.com/privacy).</li>
                    <li><strong>Icons von svgrepo.com und lucide-react:</strong> Zur Darstellung von Icons und Symbolen verwendet unsere Seite Bibliotheken wie lucide-react (Open-Source-Icon-Bibliothek) und Grafiken von svgrepo.com. Lucide-react ist in unsere Webanwendung integriert und wird lokal aus dem eigenen Code bereitgestellt – hierbei findet keine Datenübertragung an Dritte statt, da die Icons im Rahmen unseres Webcodes gerendert werden. Daneben nutzen wir in Einzelfällen Icons/Grafiken von svgrepo.com (Betreiber: SVG Repo, voraussichtlich ansässig in den USA oder einem Drittland). Wenn solche Grafiken nicht bei uns gehostet sind, sondern direkt von svgrepo-CDN geladen werden, erhält der Betreiber bei Abruf Ihre IP-Adresse und ggf. Browser-Informationen. Wir haben auch hier ein Interesse, Datenübermittlungen gering zu halten. Soweit machbar, werden SVG-Grafiken von uns heruntergeladen und lokal gehostet. Sollte eine Live-Einbindung von svgrepo erforderlich sein, holen wir – falls es sich nicht um eine technisch zwingende Auslieferung handelt – zuvor Ihre Zustimmung ein. Ansonsten binden wir externe Icons nur ein, wenn sie technisch erforderlich sind (Rechtsgrundlage dann Art. 6 Abs. 1 lit. f DSGVO i.V.m. § 25 Abs. 2 TTDSG, wobei unser Interesse die einheitliche Darstellung des Designs ist). – Empfängerhinweis: Bei Aufruf von svgrepo.com-Ressourcen werden Daten an Server außerhalb der EU übertragen (der Anbieter unterliegt nicht der DSGVO, soweit ersichtlich). Dies erfolgt nur mit Einwilligung oder im geringstmöglichen Umfang. Bitte beachten Sie die Datenschutzerklärung auf svgrepo.com für weitere Infos.</li>
                </ul>
                <br />
                <strong>Zwecke der Datenübermittlung an Dritt-Ressourcen:</strong> Darstellung unserer Website in ansprechender visueller Form (Schriftbild, Icons) und Gewährleistung eines konsistenten Layouts auf unterschiedlichen Endgeräten. Ohne externe Schriftarten/Icons müssten wir auf gestalterische Elemente verzichten oder Abstriche bei der Ladeperformance hinnehmen. Gleichwohl hat der Schutz Ihrer Daten für uns Priorität – daher der bevorzugte lokale Einsatz.
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Soweit externe Ressourcen unvermeidbar technisch notwendig eingebunden werden (z.B. um eine Funktion bereitzustellen, die ohne die externe Ressource nicht funktioniert), stützen wir dies auf Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der attraktiven Gestaltung unseres Angebots) in Kombination mit § 25 Abs. 2 TTDSG (notwendige Speicherung/Abruf). Im Regelfall jedoch erfolgt eine Einbindung erst nach Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO), insbesondere bei Google Fonts, um den Anforderungen der Rechtsprechung zu genügen. Sie können eine erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen, z.B. durch Anpassung der Cookie/Datenschutzeinstellungen auf unserer Website.
                <br /><br />
                <strong>Empfänger:</strong> Google Fonts: Google Ireland Ltd. (siehe oben) bzw. Google LLC, USA; svgrepo: SVG Repo (USA); lucide-react: wird von uns selbst gehostet, kein externer Empfänger. Diese Empfänger erhalten Ihre IP-Adresse und die erforderlichen technischen Informationen zum Abruf der Dateien. Google ist nach DPF zertifiziert (Datenübermittlung in die USA zulässig). Bei anderen (svgrepo) bestehen ggf. keine entsprechenden Garantien – hierüber klären wir Sie im Einwilligungsprozess gesondert auf, und die Übertragung erfolgt nur, wenn Sie zustimmen (Art. 49 Abs. 1 lit. a DSGVO in Ermangelung anderer Garantien).
                <br /><br />
                <strong>Speicherdauer:</strong> Wir selbst speichern in diesem Zusammenhang keine personenbezogenen Daten. Die Anfrage-Logs bei den Drittanbietern (z.B. Google) werden dort nach deren Vorgaben gespeichert; nach unserer Kenntnis speichert Google die Requests zu Fonts nur kurz und in aggregierter Form. Etwaige Consent-Entscheidungen des Nutzers werden bei uns in einem Consent-Cookie für 3 Monate gespeichert, sofern Sie zugestimmt haben, damit wir Ihre Wahl beachten können. Dieses Cookie können Sie jederzeit über Ihre Browser-Einstellungen löschen.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">8. Nutzung externer APIs und Datenquellen</h2>
            <p className="mb-4">
                Unsere Website bindet an manchen Stellen externe Datenquellen über APIs (Programmierschnittstellen) ein, um Ihnen aktuelle Informationen bereitzustellen (z.B. Wetterdaten oder öffentliche Verkehrsauskunft). Wenn Sie solche Funktionen nutzen, wird Ihr Browser eine Anfrage an den jeweiligen API-Anbieter stellen. Dabei werden – analog zu Abschnitt 5 – bestimmte technische Daten (insb. Ihre IP-Adresse) an den API-Anbieter übermittelt, und je nach Art der Anfrage können auch inhaltliche Parameter (wie eine Standortangabe oder eine Suchanfrage) übermittelt werden. Wir bemühen uns, Ihre personenbezogenen Daten auch hierbei zu schützen, z.B. durch Anonymisierung von Anfragen, wann immer möglich. Im Detail nutzen wir folgende APIs:
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>Open-Meteo Wetterdaten:</strong> Für die Anzeige von Wetterinformationen (z.B. in Projekten) verwenden wir die API von Open-Meteo (OpenMeteo GmbH, Hintere Schilligmatte 6, 6463 Bürglen, Schweiz). Wenn Sie eine Seite aufrufen, die Wetterdaten anzeigt, fragt unser System die benötigten Wettervorhersagen von api.open-meteo.com ab. Hierbei wird typischerweise der geographische Standort (z.B. Koordinaten oder Ortsname) in der Anfrage übermittelt, um das ortsspezifische Wetter zu erhalten. Open-Meteo erhält durch diesen Abruf Ihre IP-Adresse und die Parameter der Anfrage. Open-Meteo speichert nach eigenen Angaben keine personenbezogenen Daten dauerhaft und teilt keine persönlichen Informationen mit Dritten. Technisch werden IP-Adressen möglicherweise kurzfristig in Server-Logfiles gehalten, etwa um Missbrauch (zu hohe Abrufraten) zu erkennen; laut Open-Meteo werden solche Logdaten jedoch nach 90 Tagen gelöscht. Die Wetterdaten selbst werden uns zurückgeliefert und im Browser angezeigt. Eine weitergehende Verarbeitung Ihrer Daten durch uns findet nicht statt. – Datentransfer Schweiz: Die Schweiz gilt datenschutzrechtlich als Drittland mit angemessenem Schutzniveau (Angemessenheitsbeschluss der EU-Kommission liegt vor), sodass die Übermittlung Ihrer Anfrage an Open-Meteo zulässig ist.</li>
                </ul>
                <br />
                <strong>Zweck:</strong> Bereitstellung von aktuellen Wetterinformationen als funktionaler Bestandteil unseres Angebots, entsprechend Ihrer Anfrage.
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse, unser Angebot durch nützliche Informationen zu erweitern). Die Verarbeitung der IP bei Open-Meteo ist technisch notwendig, um die Daten abzurufen (vergleichbar mit Abschnitt 7). Eine Einwilligung ist hier nicht erforderlich, da keine über die Anfrage hinausgehende Tracking-Verarbeitung erfolgt und Open-Meteo keine persönlichen Profile erstellt.
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>BVG-ÖPNV-Daten:</strong> In unserem Projekt quiz.zacklack.de oder anderen experimentellen Seiten binden wir unter Umständen Informationen des öffentlichen Nahverkehrs (Fahrpläne, Verbindungsabfragen) ein. Hierzu nutzen wir die API der Berliner Verkehrsbetriebe (BVG) bzw. des Verkehrsverbundes Berlin-Brandenburg (VBB). Konkret könnten wir einen Dienst wie v6.bvg.transport.rest (eine öffentliche inoffizielle BVG-API) nutzen. Wenn Sie eine solche Funktion (z.B. „Finde die nächste Verbindung") nutzen, wird Ihr Browser eine Anfrage an die BVG/VBB-API stellen, die z.B. Start- und Zielhaltestelle oder eine Liniennummer enthält. Die BVG-Server erhalten dadurch Ihre IP-Adresse und die Anfrageinhalte. Diese Daten werden dort verarbeitet, um die passenden Auskünfte (z.B. nächste Abfahrtszeiten) zurückzusenden. Nach unserem Verständnis werden dabei keine persönlichen Profile gebildet – die Anfrage dient ausschließlich der Live-Auskunft. Die BVG unterliegt als öffentliches Unternehmen den Datenschutzbestimmungen des Bundes und Landes Berlin; personenbezogene Daten werden gemäß deren Datenschutzerklärung behandelt. Wir erhalten von der API lediglich die angeforderten Informationen und zeigen sie an; wir speichern keine persönlichen Daten des Nutzers bei dieser Funktion.</li>
                </ul>
                <br />
                <strong>Zweck:</strong> Bereitstellung von ÖPNV-Informationen auf Nutzeranfrage (z.B. im Rahmen eines Quiz oder Informationsangebots).
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. b DSGVO, sofern man die Abfrage als vom Nutzer initiierten (vor)vertraglichen Vorgang betrachtet (Informationserteilung auf Anfrage ist Teil unseres unentgeltlichen Nutzungsverhältnisses). Hilfsweise Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an Nutzerfreundlichkeit unseres Angebots durch hilfreiche Zusatzinformationen). Eine Einwilligung ist nicht erforderlich, da die Datenübertragung vom Nutzer durch die Anfrage selbst angestoßen wird und für die Erfüllung der gewünschten Funktion notwendig ist.
                <br /><br />
                <strong>Empfänger und Hinweis:</strong> Empfänger ist die BVG / VBB (oder der Betreiber der API transport.rest, welcher in Europa gehostet wird). Diese Stellen verarbeiten die Daten entsprechend ihrer eigenen Datenschutzhinweise. Eine Übermittlung in Drittländer findet unseres Wissens hierbei nicht statt, da die Server in Deutschland stehen. Sollte ein anderer externer Dienst für ÖPNV-Daten eingebunden werden, informieren wir Sie entsprechend.
                <br /><br />
                <em>(Weitere APIs: Unser Webangebot wird fortlaufend weiterentwickelt. Sollte künftig eine zusätzliche externe API eingebunden werden – etwa Kartendienste, Social-Media-Feeds o.ä. – werden wir an dieser Stelle darüber informieren und die datenschutzrelevanten Details ergänzen.)</em>
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">9. Analytik und Reichweitenmessung (Umami Analytics)</h2>
            <p className="mb-4">
                Wir setzen ein Web-Analysewerkzeug ein, um die Nutzung unseres Webangebots auszuwerten und es stetig verbessern zu können. Anders als gängige Dienste (z.B. Google Analytics) handelt es sich hierbei um eine datenschutzfreundliche, selbst gehostete Lösung namens Umami Analytics.
                <br /><br />
                <strong>Beschreibung der Verarbeitung:</strong> Umami erfasst bei Seitenaufruf bestimmte Nutzungsdaten, darunter insbesondere: welche Seite aufgerufen wurde, zu welchem Zeitpunkt, von welcher vorherigen Seite der Besucher kam (Referrer), welches Land der Zugriff ungefähr zuzuordnen ist (anhand der IP, die jedoch nicht gespeichert, sondern nur zur Geolokalisierung in Länder aufgelöst und dann verworfen wird) sowie technische Informationen zum Browser/Endgerät (User-Agent, Bildschirmgröße). Persönlich identifizierende Informationen erhebt Umami dabei nicht – das heißt, es werden keine vollständigen IP-Adressen gespeichert, keine Cookies gesetzt, keine Geräte-ID oder ähnliches genutzt, um einen wiederkehrenden Besucher zu erkennen. Alle erfassten Datenpunkte werden unmittelbar aggregiert und anonymisiert. Beispielsweise sehen wir statistisch, welche unserer Seiten wie oft besucht wurden, aus welchem Land Zugriffe kommen und welche Browser benutzt wurden. Wir können jedoch nicht nachvollziehen, welche Seiten ein individueller Nutzer im Detail besucht hat. Es findet keinerlei geräteübergreifendes Tracking statt. Umami arbeitet komplett ohne Cookies und respektiert den „Do-Not-Track"-Header Ihres Browsers (d.h. wenn Sie in Ihrem Browser die Einstellung gesetzt haben, nicht getrackt zu werden, wird Umami Ihren Besuch gar nicht erst erfassen). Wir betreiben Umami auf eigener Server-Infrastruktur (keine Datenübermittlung an Dritte). Die Analysedaten werden in einer Datenbank gespeichert (gehostet in unserem Verantwortungsbereich, siehe Hosting unter Abschnitt 5 – aktuell nutzen wir hierfür die MongoDB Atlas Cloud-Datenbank, Standort Frankfurt, verwaltet durch MongoDB, Inc. als Auftragsverarbeiter).
                <br /><br />
                <strong>Zweck:</strong> Zweck der Nutzung von Umami ist die Reichweitenmessung und Verbesserung unseres Webangebots. Wir erfahren durch die anonymen Statistiken z.B., welche Inhalte besonders gefragt sind oder welche Browserspezifikationen wir berücksichtigen müssen. Dies hilft uns, technische Optimierungen vorzunehmen und Inhalte nutzerfreundlicher zu gestalten. Da wir keinerlei persönliche Profile bilden, erfolgt die Analyse rein auf aggregierter Ebene zur Erfolgsmessung unserer Seiten (z.B. Anzahl Besucher pro Tag, beliebtesten Unterseiten, etc.).
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der fortlaufenden Verbesserung unseres Online-Angebots und Auswertung der Nutzung in datenschutzkonformer Weise). Wir haben bewusst eine Lösung gewählt, die DSGVO- und ePrivacy-konform arbeitet und keine Einwilligung erfordert, da keine personenbezogenen Daten im Sinne der DSGVO verarbeitet werden. Die DSK (Konferenz der Datenschutzaufsichtsbehörden) hat klargestellt, dass für truly anonymisierte Analytics keine Einwilligungspflicht besteht. Dennoch respektieren wir Ihren Willen: haben Sie Do-Not-Track aktiviert, bleibt Ihr Besuch komplett ungezählt. Selbstverständlich können Sie der Analyse auch sonst jederzeit widersprechen – dazu genügt z.B. das Setzen eines Opt-Out-Headers oder der Nutzung von Browser-Blocking (da Umami keine Cookies nutzt, gibt es kein klassisches Opt-Out-Cookie; aber wie erwähnt werden Sie bei DNT gar nicht erst erfasst).
                <br /><br />
                <strong>Empfänger:</strong> Die Analytics-Daten werden nicht an Dritte weitergegeben. Weder wir noch Umami teilen die Statistiken mit externen Anbietern. Die Daten liegen auf unserem Server bzw. in unserer Datenbank (MongoDB Atlas im Rahmen der Auftragsverarbeitung). MongoDB könnte als technischer Dienstleister im Wartungsfall Zugang erlangen, ist jedoch vertraglich gebunden und selbst DSGVO-konform zertifiziert (u.a. nach ISO 27001, und es bestehen EU-Standardvertragsklauseln mit dem Anbieter). Es findet keine Übermittlung in Drittstaaten an unbekannte Empfänger statt, da wir die Kontrolle über die Daten behalten. (MongoDB mit Sitz in den USA ist Auftragsverarbeiter; durch Serverstandort EU und vertragliche SCC ist ein angemessenes Schutzniveau gewährleistet. Ein Restrisiko kann theoretisch durch US-Behördenzugriff bestehen, siehe Abschnitt Drittländer, doch die Daten sind anonym und wenig aussagekräftig.)
                <br /><br />
                <strong>Speicherdauer:</strong> Die Rohdaten der Seitenaufrufe (die bereits anonym sind) werden in unserer Datenbank für unbestimmte Zeit gespeichert, um langfristige Trends zu analysieren. Eine regelmäßige Löschung ist derzeit nicht vorgesehen, da keine personenbezogenen Informationen enthalten sind. Sollten wir feststellen, dass ältere Statistikdaten nicht mehr benötigt werden, können wir diese entfernen, ohne Auswirkungen auf Ihre Rechte, da kein Personenbezug vorliegt. Sie haben gleichwohl das Recht, uns zu fragen, ob Daten zu Ihrer Person in den Statistiken enthalten sind – wir können dies nur insoweit beantworten, dass grundsätzlich keine identifizierenden Daten vorliegen. Einzelne Seitenaufrufe lassen sich nicht auf Sie zurückführen, daher ist ein Berichtigungs- oder Löschbegehren hier abstrakt kaum anwendbar (siehe dazu auch Ihre Rechte unten).
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">10. Google Search Console (Website-Analyse durch Google)</h2>
            <p className="mb-4">
                Wir nutzen Google Search Console, einen kostenlosen Dienst von Google, der uns hilft, die Präsenz unserer Website in den Google-Suchergebnissen zu überwachen und zu optimieren. In diesem Zusammenhang möchten wir der Vollständigkeit halber erwähnen, wie Daten verarbeitet werden, obwohl dieser Dienst keine direkten personenbezogenen Daten unserer Webseitenbesucher an uns weitergibt.
                <br /><br />
                <strong>Beschreibung und Umfang:</strong> Die Search Console liefert uns aggregierte Auswertungen darüber, bei welchen Suchbegriffen unsere Seite in Google erschienen ist, wie oft darauf geklickt wurde, welche durchschnittliche Position erzielt wurde, sowie technische Berichte (z.B. ob alle Seiten erfolgreich von Google indexiert werden konnten). Diese Daten stammen ausschließlich von Google selbst – genauer gesagt aus den Interaktionen der Nutzer mit der Google-Suchmaschine. Sobald ein Nutzer von der Google-Suche auf unsere Webseite klickt, enden die Erhebungen der Search Console. Google erfasst also die Suchanfrage und den Klick, stellt uns diese Information aber nur in zusammengefasster Form bereit (etwa: wie oft ein bestimmter Suchbegriff zu unserer Seite führte). Wir erhalten keine personenbezogenen Daten einzelner Nutzer, insbesondere keine IP-Adressen, keine individuellen Suchhistorien oder ähnliches. Es ist uns nicht möglich, über die Search Console einen bestimmten Besucher unserer Website zu identifizieren. Google selbst kennt natürlich den Nutzer (sofern angemeldet) bzw. zumindest dessen IP/Browser – das bleibt aber auf Seiten von Google und unterliegt deren Kontrolle.
                <br /><br />
                <strong>Zweck:</strong> Unser berechtigtes Interesse liegt darin, die Auffindbarkeit unserer Website zu verbessern und technische Probleme im Zusammenhang mit der Google-Indexierung zu erkennen. Die Search Console hilft z.B. festzustellen, ob bestimmte Seiten nicht in den Suchindex aufgenommen wurden oder für welche Inhalte wir bei Nutzern Anklang finden. Diese Informationen nutzen wir zur Suchmaschinenoptimierung (SEO) und Verbesserung der Inhalte.
                <br /><br />
                <strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Optimierung unseres Webauftritts). Da über die Search Console keine Nutzerbezogenen Daten von unserer Website aus erhoben werden, sondern Google uns eigene Auswertungen bereitstellt, greifen hier die Pflichten der DSGVO nur sehr eingeschränkt. Wir erfassen selbst in diesem Rahmen keine personenbezogenen Besucherinformationen. Die Nutzung der Google-Suche durch Endnutzer unterliegt den Nutzungsbedingungen und der Datenschutzerklärung von Google – der Nutzer hat insoweit gegenüber Google eingewilligt, dass seine Suchaktionen analysiert werden. Für uns erfolgt die Bereitstellung der aggregierten Reports datenschutzkonform, ohne dass besondere Einwilligungen einzuholen wären.
                <br /><br />
                <strong>Empfänger:</strong> Empfänger der personenbezogenen Daten (Suchbegriffe, IP etc.) ist hier primär Google selbst. Google tritt uns gegenüber nur als Datenquellen-Bereitsteller auf, nicht als Auftragsverarbeiter. Die Google Ireland Ltd. (Irland) ist Verantwortliche für die Datenverarbeitung im Rahmen der Google-Dienste in Europa. Wir erhalten von Google lediglich Auswertungen über ein passwortgeschütztes Konto. In diesem Konto sind keine personenbezogenen Daten der Nutzer enthalten, lediglich aggregierte Leistungsdaten unserer Website. Wir behandeln diese Reports vertraulich und teilen sie nicht mit Unbefugten. Google speichert die Rohdaten der Suchanfragen gemäß der eigenen Datenschutzerklärung; darauf haben wir keinen Einfluss. Eine Übermittlung von personenbezogenen Daten aus der Search Console an uns oder andere Dritte findet nicht statt.
                <br /><br />
                <strong>Hinweis:</strong> Streng genommen müsste die Nutzung der Search Console nicht in der Datenschutzerklärung aufgeführt werden, da sie – wie erläutert – keine Verarbeitungen personenbezogener Daten durch uns an den Website-Besuchern beinhaltet. Wir erwähnen den Dienst dennoch aus Transparenzgründen. Für weitere Informationen, wie Google mit Ihren Daten umgeht, verweisen wir auf die allgemeine Datenschutzerklärung von Google (https://policies.google.com) und die Hilfeseiten zur Search Console.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">11. Weitere Empfänger von Daten und eingesetzte Auftragsverarbeiter</h2>
            <p className="mb-4">
                Neben den bereits genannten speziellen Empfängern (Hosting-Provider, Cloudflare, API-Betreiber etc.) können im Rahmen des Betriebs dieser Website weitere Stellen Daten erhalten, sei es im Rahmen einer Auftragsverarbeitung oder einer gesetzlichen Verpflichtung. Eine Übersicht:
                <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li><strong>E-Mail-Kommunikation:</strong> Wenn Sie uns eine E-Mail schreiben (z.B. an eine der angegebenen Kontaktadressen wie admin@zacklack.de), verarbeiten wir Ihre E-Mail-Adresse und die von Ihnen übermittelten Informationen zum Zweck der Bearbeitung Ihrer Anfrage. Solche E-Mails liegen auf den Servern unseres E-Mail-Providers (z.B. imap.zacklack.de, betrieben durch [den Mail-Dienst, ggf. ebenfalls Cloudflare oder einen anderen Provider]) und werden von uns vertraulich behandelt. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse, Anfragen zu beantworten); sofern die Kontaktaufnahme auf den Abschluss eines Vertrags abzielt oder in Zusammenhang mit einem bestehenden Nutzungsverhältnis steht, auch Art. 6 Abs. 1 lit. b DSGVO. Wir geben E-Mail-Inhalte nicht ohne Ihre Einwilligung weiter. Bitte beachten Sie, dass die Übertragung von E-Mails unverschlüsselt erfolgen kann – nutzen Sie auf Wunsch PGP o.ä. für sensitive Inhalte.</li>
                    <li><strong>Datenbanken:</strong> Für die Speicherung von Daten im Hintergrund nutzen wir Datenbankdienste. Bereits genannt wurden db4free.net (ein Test-MySQL-Dienst, betrieben in Österreich) und MongoDB Atlas (Cloud-Datenbankdienst von MongoDB, Inc., mit Servern in der EU). Diese Dienste fungieren als Auftragsverarbeiter, indem sie für uns Daten hosten. Die MySQL-Datenbank bei db4free.net verwenden wir ausschließlich für nicht-kritische Testdaten und Entwicklungszwecke – es werden hier in der Regel keine produktiven Personendaten dauerhaft gespeichert. Da db4free.net ein Community-Projekt ist, das den österreichischen Datenschutzgesetzen unterliegt, gehen wir von einem verantwortungsvollen Umgang aus; jedoch ist zu beachten, dass es sich nicht um einen professionellen Dienst mit SLA handelt, sondern um einen kostenlosen Testservice (wir speichern dort keine sensiblen Informationen). Die MongoDB Atlas-Datenbank hostet u.a. die Daten unseres Umami-Analytics-Tools und ggf. anderer Dienste. MongoDB hat als Unternehmen seinen Sitz in den USA; durch Rechenzentrumsstandorte in Deutschland/Europa und vertragliche Garantien (Standardklauseln) wird ein angemessenes Datenschutzniveau zugesichert. Empfänger dieser Daten ist technisch MongoDB, Inc. (Auftragsverarbeiter). Wir behalten jedoch die alleinige Kontrolle über die Daten und MongoDB darf sie nicht zu eigenen Zwecken auswerten.</li>
                    <li><strong>Sonstige Dienstleister:</strong> Gelegentlich bedienen wir uns weiterer externer Tools im Rahmen der Website, z.B. für Entwicklungszwecke (Continuous Deployment Tools, Status-Monitoring via Uptime Kuma, etc.). Solche Tools könnten im Einzelfall Logdaten einsehen (z.B. wenn unser Statusmonitor erkennt, dass die Seite down ist, protokolliert er Zeit und Grund). Diese technischen Meta-Daten betreffen aber keine Nutzerinhalte und enthalten höchstens Server-Statusinformationen. Sollte eine Verarbeitung personenbezogener Daten durch solche Tools stattfinden, geschieht dies ebenfalls auf Basis von Auftragsverarbeitungsverträgen und innerhalb zulässiger Grenzen.</li>
                    <li><strong>Gesetzliche Offenlegung:</strong> Schließlich können wir verpflichtet sein, Daten an Behörden, Gerichte oder andere öffentliche Stellen weiterzugeben, sofern eine gesetzliche Verpflichtung besteht (Art. 6 Abs. 1 lit. c DSGVO). Beispielsweise auf Anfrage der Strafverfolgungsbehörden im Rahmen geltenden Rechts oder zur Gefahrenabwehr. In solchen Fällen erfolgt die Herausgabe nur im gesetzlichen Rahmen und nach sorgfältiger Prüfung.</li>
                </ul>
                <br />
                Wir verkaufen oder vermieten Ihre Daten niemals an Dritte. Eine Übermittlung zu Marketingzwecken an Drittanbieter findet nicht statt.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Widerruf Ihrer Einwilligung und Widerspruchsrecht</h2>
            <p className="mb-4">
                Viele Datenverarbeitungsvorgänge basieren auf Ihrer Einwilligung (vgl. Art. 7 DSGVO). Diese können Sie jederzeit widerrufen, ohne dass die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung berührt wird. Ferner haben Sie das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, der Verarbeitung Ihrer personenbezogenen Daten zu widersprechen (vgl. Art. 21 DSGVO).
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Beschwerderecht bei der zuständigen Aufsichtsbehörde</h2>
            <p className="mb-4">
                Sollten Sie den Eindruck haben, dass die Verarbeitung Ihrer personenbezogenen Daten gegen die geltenden Datenschutzbestimmungen verstößt, steht Ihnen das Recht zu, sich bei der zuständigen Aufsichtsbehörde zu beschweren. Zuständig hierfür ist in der Regel die Aufsichtsbehörde Ihres gewöhnlichen Aufenthalts oder des Ortes, an dem der mutmaßliche Verstoß stattgefunden hat.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Recht auf Datenübertragbarkeit</h2>
            <p className="mb-4">
                Sie haben das Recht, Ihre personenbezogenen Daten, die auf Grundlage Ihrer Einwilligung oder zur Vertragserfüllung automatisiert verarbeitet werden, in einem gängigen, maschinenlesbaren Format zu erhalten und diese Daten an einen anderen Verantwortlichen zu übermitteln (vgl. Art. 20 DSGVO).
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Auskunft, Berichtigung und Löschung</h2>
            <p className="mb-4">
                Sie haben jederzeit das Recht auf unentgeltliche Auskunft über Ihre bei uns gespeicherten personenbezogenen Daten, deren Herkunft, Empfänger und den Zweck der Datenverarbeitung (vgl. Art. 15 DSGVO). Ferner haben Sie das Recht, unrichtige Daten berichtigen zu lassen sowie unter Beachtung gesetzlicher Vorgaben die Löschung Ihrer personenbezogenen Daten zu verlangen (vgl. Art. 16 und 17 DSGVO).
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Recht auf Einschränkung der Verarbeitung</h2>
            <p className="mb-4">
                Unter bestimmten Voraussetzungen haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Dies gilt beispielsweise, wenn Sie die Richtigkeit der Daten bestreiten oder wenn die Verarbeitung unrechtmäßig erfolgt ist. In diesen Fällen werden die Daten – abgesehen von der Speicherung – nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen weiterverarbeitet.
            </p>

            <p className="mt-8 text-sm text-gray-400">
                Stand: 08.02.2025
            </p>
        </section>
    );
};

export default Policy;